package br.com.integracampeonatobrasileiro.hbnobj;
// Generated 22/02/2018 16:55:34 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DatajogosId generated by hbm2java
 */
public class DatajogosId  implements java.io.Serializable {


     private Date data;
     private int cdJogo;

    public DatajogosId() {
    }

    public DatajogosId(Date data, int cdJogo) {
       this.data = data;
       this.cdJogo = cdJogo;
    }
   
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public int getCdJogo() {
        return this.cdJogo;
    }
    
    public void setCdJogo(int cdJogo) {
        this.cdJogo = cdJogo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DatajogosId) ) return false;
		 DatajogosId castOther = ( DatajogosId ) other; 
         
		 return ( (this.getData()==castOther.getData()) || ( this.getData()!=null && castOther.getData()!=null && this.getData().equals(castOther.getData()) ) )
 && (this.getCdJogo()==castOther.getCdJogo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getData() == null ? 0 : this.getData().hashCode() );
         result = 37 * result + this.getCdJogo();
         return result;
   }   


}


