package br.com.integracampeonatobrasileiro.hbnobj;
// Generated 22/02/2018 16:55:34 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Jogoid generated by hbm2java
 */
public class Jogoid  implements java.io.Serializable {


     private int cdJogo;
     private Equipe equipeByCdEquipe2;
     private Equipe equipeByCdEquipe1;
     private Boolean stClassificougolsfora;
     private Date dtJogo;
     private String dspTime1;
     private String dspTime2;
     private Boolean stEliminoujogovolta;
     private String dsEstadio;
     private String hrJogo;
     private String dsLocal;
     private String nrJogo;
     private String plPenalti1;
     private String plPenalti2;
     private String plTime1;
     private String plTime2;
     private String psJogo;
     private String nrRodada;
     private String urlPosjogo;
     private String urlPrejogo;
     private String urlVideo;
     private Set datajogoses = new HashSet(0);
     private Set rodadajogoses = new HashSet(0);

    public Jogoid() {
    }

	
    public Jogoid(int cdJogo, Equipe equipeByCdEquipe2, Equipe equipeByCdEquipe1) {
        this.cdJogo = cdJogo;
        this.equipeByCdEquipe2 = equipeByCdEquipe2;
        this.equipeByCdEquipe1 = equipeByCdEquipe1;
    }
    public Jogoid(int cdJogo, Equipe equipeByCdEquipe2, Equipe equipeByCdEquipe1, Boolean stClassificougolsfora, Date dtJogo, String dspTime1, String dspTime2, Boolean stEliminoujogovolta, String dsEstadio, String hrJogo, String dsLocal, String nrJogo, String plPenalti1, String plPenalti2, String plTime1, String plTime2, String psJogo, String nrRodada, String urlPosjogo, String urlPrejogo, String urlVideo, Set datajogoses, Set rodadajogoses) {
       this.cdJogo = cdJogo;
       this.equipeByCdEquipe2 = equipeByCdEquipe2;
       this.equipeByCdEquipe1 = equipeByCdEquipe1;
       this.stClassificougolsfora = stClassificougolsfora;
       this.dtJogo = dtJogo;
       this.dspTime1 = dspTime1;
       this.dspTime2 = dspTime2;
       this.stEliminoujogovolta = stEliminoujogovolta;
       this.dsEstadio = dsEstadio;
       this.hrJogo = hrJogo;
       this.dsLocal = dsLocal;
       this.nrJogo = nrJogo;
       this.plPenalti1 = plPenalti1;
       this.plPenalti2 = plPenalti2;
       this.plTime1 = plTime1;
       this.plTime2 = plTime2;
       this.psJogo = psJogo;
       this.nrRodada = nrRodada;
       this.urlPosjogo = urlPosjogo;
       this.urlPrejogo = urlPrejogo;
       this.urlVideo = urlVideo;
       this.datajogoses = datajogoses;
       this.rodadajogoses = rodadajogoses;
    }
   
    public int getCdJogo() {
        return this.cdJogo;
    }
    
    public void setCdJogo(int cdJogo) {
        this.cdJogo = cdJogo;
    }
    public Equipe getEquipeByCdEquipe2() {
        return this.equipeByCdEquipe2;
    }
    
    public void setEquipeByCdEquipe2(Equipe equipeByCdEquipe2) {
        this.equipeByCdEquipe2 = equipeByCdEquipe2;
    }
    public Equipe getEquipeByCdEquipe1() {
        return this.equipeByCdEquipe1;
    }
    
    public void setEquipeByCdEquipe1(Equipe equipeByCdEquipe1) {
        this.equipeByCdEquipe1 = equipeByCdEquipe1;
    }
    public Boolean getStClassificougolsfora() {
        return this.stClassificougolsfora;
    }
    
    public void setStClassificougolsfora(Boolean stClassificougolsfora) {
        this.stClassificougolsfora = stClassificougolsfora;
    }
    public Date getDtJogo() {
        return this.dtJogo;
    }
    
    public void setDtJogo(Date dtJogo) {
        this.dtJogo = dtJogo;
    }
    public String getDspTime1() {
        return this.dspTime1;
    }
    
    public void setDspTime1(String dspTime1) {
        this.dspTime1 = dspTime1;
    }
    public String getDspTime2() {
        return this.dspTime2;
    }
    
    public void setDspTime2(String dspTime2) {
        this.dspTime2 = dspTime2;
    }
    public Boolean getStEliminoujogovolta() {
        return this.stEliminoujogovolta;
    }
    
    public void setStEliminoujogovolta(Boolean stEliminoujogovolta) {
        this.stEliminoujogovolta = stEliminoujogovolta;
    }
    public String getDsEstadio() {
        return this.dsEstadio;
    }
    
    public void setDsEstadio(String dsEstadio) {
        this.dsEstadio = dsEstadio;
    }
    public String getHrJogo() {
        return this.hrJogo;
    }
    
    public void setHrJogo(String hrJogo) {
        this.hrJogo = hrJogo;
    }
    public String getDsLocal() {
        return this.dsLocal;
    }
    
    public void setDsLocal(String dsLocal) {
        this.dsLocal = dsLocal;
    }
    public String getNrJogo() {
        return this.nrJogo;
    }
    
    public void setNrJogo(String nrJogo) {
        this.nrJogo = nrJogo;
    }
    public String getPlPenalti1() {
        return this.plPenalti1;
    }
    
    public void setPlPenalti1(String plPenalti1) {
        this.plPenalti1 = plPenalti1;
    }
    public String getPlPenalti2() {
        return this.plPenalti2;
    }
    
    public void setPlPenalti2(String plPenalti2) {
        this.plPenalti2 = plPenalti2;
    }
    public String getPlTime1() {
        return this.plTime1;
    }
    
    public void setPlTime1(String plTime1) {
        this.plTime1 = plTime1;
    }
    public String getPlTime2() {
        return this.plTime2;
    }
    
    public void setPlTime2(String plTime2) {
        this.plTime2 = plTime2;
    }
    public String getPsJogo() {
        return this.psJogo;
    }
    
    public void setPsJogo(String psJogo) {
        this.psJogo = psJogo;
    }
    public String getNrRodada() {
        return this.nrRodada;
    }
    
    public void setNrRodada(String nrRodada) {
        this.nrRodada = nrRodada;
    }
    public String getUrlPosjogo() {
        return this.urlPosjogo;
    }
    
    public void setUrlPosjogo(String urlPosjogo) {
        this.urlPosjogo = urlPosjogo;
    }
    public String getUrlPrejogo() {
        return this.urlPrejogo;
    }
    
    public void setUrlPrejogo(String urlPrejogo) {
        this.urlPrejogo = urlPrejogo;
    }
    public String getUrlVideo() {
        return this.urlVideo;
    }
    
    public void setUrlVideo(String urlVideo) {
        this.urlVideo = urlVideo;
    }
    public Set getDatajogoses() {
        return this.datajogoses;
    }
    
    public void setDatajogoses(Set datajogoses) {
        this.datajogoses = datajogoses;
    }
    public Set getRodadajogoses() {
        return this.rodadajogoses;
    }
    
    public void setRodadajogoses(Set rodadajogoses) {
        this.rodadajogoses = rodadajogoses;
    }




}


