package br.com.integracampeonatobrasileiro.hbnobj;
// Generated 22/02/2018 16:55:34 by Hibernate Tools 4.3.1



/**
 * Rodadajogos generated by hbm2java
 */
public class Rodadajogos  implements java.io.Serializable {


     private RodadajogosId id;
     private Jogoid jogoid;

    public Rodadajogos() {
    }

    public Rodadajogos(RodadajogosId id, Jogoid jogoid) {
       this.id = id;
       this.jogoid = jogoid;
    }
   
    public RodadajogosId getId() {
        return this.id;
    }
    
    public void setId(RodadajogosId id) {
        this.id = id;
    }
    public Jogoid getJogoid() {
        return this.jogoid;
    }
    
    public void setJogoid(Jogoid jogoid) {
        this.jogoid = jogoid;
    }




}


