package br.com.integracampeonatobrasileiro.hbnobj;
// Generated 22/02/2018 16:55:34 by Hibernate Tools 4.3.1



/**
 * RodadajogosId generated by hbm2java
 */
public class RodadajogosId  implements java.io.Serializable {


     private int cdRodada;
     private int cdJogo;

    public RodadajogosId() {
    }

    public RodadajogosId(int cdRodada, int cdJogo) {
       this.cdRodada = cdRodada;
       this.cdJogo = cdJogo;
    }
   
    public int getCdRodada() {
        return this.cdRodada;
    }
    
    public void setCdRodada(int cdRodada) {
        this.cdRodada = cdRodada;
    }
    public int getCdJogo() {
        return this.cdJogo;
    }
    
    public void setCdJogo(int cdJogo) {
        this.cdJogo = cdJogo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RodadajogosId) ) return false;
		 RodadajogosId castOther = ( RodadajogosId ) other; 
         
		 return (this.getCdRodada()==castOther.getCdRodada())
 && (this.getCdJogo()==castOther.getCdJogo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCdRodada();
         result = 37 * result + this.getCdJogo();
         return result;
   }   


}


